# vim: ft=tmux

# source ~/.config/tmux/plugins.conf
source ~/.config/tmux/statusline.conf

set-option -g default-terminal 'xterm-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'


unbind C-b
set -g prefix C-t
set -g repeat-time 0 # check what this does
set -g focus-events on # check what this does

# Key bindings
set-window-option -g mode-keys vi # check what this does

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Reload settings
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a

# Better splitting
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# resize panes
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

set -g mouse on

# Swap windows
bind-key -n C-S-Left swap-window -t -1 \; previous-window
bind-key -n C-S-Right swap-window -t +1 \; next-window

